disabled_rules:
  - type_name
  - identifier_name
  - trailing_comma
  - sorted_imports
  - todo

opt_in_rules:
  - convenience_type
  - discouraged_optional_collection
  - empty_count
  - empty_string
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - sorted_first_last
  - sorted_imports
  - static_operator
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - yoda_condition

excluded:
  - .build

line_length:
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
  warning: 250
  error: 300

function_body_length: 100

large_tuple:
  warning: 3
  error: 4

